# 全局日志级别设置
.level = ALL

# 控制台日志输出配置
handlers = java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level = ALL
javafx.level = WARNING

# 控制台格式化器
java.util.logging.ConsoleHandler.formatter = engine.base.CustomFormatter
